services:
  ros:
    build: .
    container_name: ros2_jazzy
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./src:/ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/tmp/.Xauthority:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: sleep infinity
